[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
itertools = "0.13"
scan_fmt = "0.2"
regex = "1"
lazy_static = "1"
